language: cpp
dist: bionic
os: linux
addons:
  apt:
    packages:
      - g++-6
      - g++-7
      - g++-8
      - clang-4.0
      - clang-5.0
      - clang-6.0
      - clang-8
      - pkg-config
      - libavformat-dev
      - libao-dev
      - libavdevice-dev
      - libmpg123-dev
      - libvorbis-dev
      - audacious-dev

jobs:
  include:
    - name: "Compiler GCC 6"
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - name: "Compiler GCC 7"
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: "Compiler GCC 8"
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - name: "Compiler Clang 4"
      env:
         - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - name: "Compiler Clang 5"
      env:
         - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - name: "Compiler Clang 6"
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - name: "Compiler Clang 8"
      env:
         - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DUSE_FDKAAC=OFF ..
  - make -j4